/// <reference types="astro/client" />
/// <reference types="@astrojs/cloudflare/types.d.ts" />

/**
 * Bindings and vars are generated by `wrangler types` into worker-configuration.d.ts.
 * Secrets are set with `wrangler secret put` / .dev.vars and never committed, so
 * wrangler cannot infer them — they are declared here.
 */
declare namespace Cloudflare {
  interface Env {
    PERPLEXITY_API_KEY: string
    OPENAI_API_KEY: string
    GEMINI_API_KEY: string
    CLORO_API_KEY: string
  }
}
